#!/bin/sh
## default programs
export TERMINAL="st"
export EDITOR="nvim"
#export VISUAL="$TERMINAL -e $EDITOR"
export BROWSER="firefox"
export PAGER="bat"

# xdg
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_RUNTIME_DIR=$HOME/.local/run

export XDG_DESKTOP_DIR="/dev/null"
export XDG_DOCUMENTS_DIR="$HOME/dox"
export XDG_DOWNLOAD_DIR="$HOME/downloads"
export XDG_MUSIC_DIR="$HOME/mus"
export XDG_PICTURES_DIR="$HOME/pix"
export XDG_PUBLICSHARE_DIR="/dev/null"
export XDG_TEMPLATES_DIR="/dev/null"
export XDG_VIDEOS_DIR="$HOME/vids"

export PATH="$PATH:$CARGO_HOME/bin:$HOME/.local/bin:$HOME/.local/binbg"

# programs
export PIPEWIRE_RUNTIME_DIR=$XDG_RUNTIME_DIR/pipewire
export NOTESDIR=$HOME/dox/notes
export TODO_PATH=$XDG_DATA_HOME/todo

# ~/ cleanup
# languages
LANGS_HOME=$HOME/.local/share/languages
export CARGO_HOME=$LANGS_HOME/rust/cargo
export RUSTUP_HOME=$LANGS_HOME/rust/rustup
export GOPATH=$LANGS_HOME/go
export XINITRC="$XDG_CONFIG_HOME/x11/initdk"
export XAUTHORITY="$XDG_RUNTIME_DIR/x11/xauth"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/zsh/inputrc"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"

# Other program settings:
export DICS="/usr/share/stardict/dic/"
export SUDO_ASKPASS="$HOME/.local/bin/dpass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export QT_QPA_PLATFORMTHEME="gtk2" # Have QT use gtk2 theme.
export MOZ_USE_XINPUT2="1" # Mozilla smooth scrolling/touchpads.
#export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for Java applications in dwm
export SPOTIPY_CLIENT_ID="93124e908f0148e482ff023b525a1ed0"
export SPOTIPY_CLIENT_SECRET="5fdb9cc7511840358ac39c7642cfa949"
