#!/bin/sh
if [ "$1" = "t" ]; then
	pamixer -t
elif [ "$1" = "i" ] || [ "$1" = "d" ]; then
	pamixer -$1 $2 --allow-boost --set-limit $3
fi
mute=""
if [ "$(pamixer --get-volume-human)" = "muted" ]; then
	mute="/ Mute"
fi
notify-send -r 11 -a "volume" -i ~/pix/assets/icons/headphones-solid.svg "Volume" "$(pamixer --get-volume) $mute"
# dunstify -r 11 -a "volume" --hints=int:value:"$(pamixer --get-volume)"  -i ~/pix/assets/icons/headphones-solid.svg "Volume" "$(pamixer --get-volume-human)"
