#!/bin/sh
cmd=$(echo "lock\nreboot\nshutdown" | ${MYMENU:-dmenu} -p "menu")
[ $cmd ] && (
[ ! ${cmd##lock} ] && xsecurelock & xset dpms force off #$HOME/.local/scripts/lock.sh
[ ! ${cmd##reboot} ] && loginctl reboot
[ ! ${cmd##shutdown} ] && loginctl poweroff
)
