#!/bin/sh
if [ "$MYMENU" = "rofi -dmenu" ]; then
	MYMENU="rofi -dmenu -theme-str 'listview{lines: 3;}'"
fi
cmd=$(echo "lock\nreboot\nshutdown" | rofi -dmenu -theme-str 'listview{lines: 3;}' -p "powermenu")
[ $cmd ] && (
[ ! ${cmd##lock} ] && xsecurelock & xset dpms force off
[ ! ${cmd##reboot} ] && loginctl reboot
[ ! ${cmd##shutdown} ] && loginctl poweroff
)
#sudo gllock; sleep 1 && xset dpms force off
#xset dpms force off # xsecurelock
