#!/bin/sh
scrots_dir=${XDG_PICTURES_DIR:-~/pix}/scrots
mkdir -p $scrots_dir
selection="$(echo "default\nfullscreen\ncustom" | ${MYMENU:-dmenu} -p "selection")"
if [ "$selection" = "default" ]; then
	name=1
	for n in $(ls $scrots_dir/ | sed 's/.\{4\}$//' | sort); do #[0-9]*
		[ "$name" = "$n" ] && name=$(expr $name + 1)
	done
	scrot -d 1 "$scrots_dir/$name.png" && notify-send -i $scrots_dir/$name.png "dmscrot" "$name.png saved."
	exit
fi
[ "$selection" ] && name="$(echo untitled | ${MYMENU:-dmenu} -p 'name')" && name=${name%.png}
[ "$name" ] && time=$(echo 1 | ${MYMENU:-dmenu} -p 'specify delay (in integral seconds)')
[ "$time" ] && (
  [ ! "${selection##custom}" ] && scrot -s -d $time "$scrots_dir/$name.png" && notify-send -i $scrots_dir/$name.png "dmscrot" "$name.png saved."
  [ ! "${selection##fullscreen}" ] && scrot -d $time "$scrots_dir/$name.png" && notify-send -i $scrots_dir/$name.png "dmscrot" "$name.png saved."
  )
exit
