#!/bin/sh
selection="$(echo 'browser\ngoogle\nbookmarks\nsites\nurl\nyoutube\nspotify' | ${MYMENU:-dmenu} -p 'browse:')"

if [ "$selection" =  "browser" ]; then
	browser="$(echo 'vimb\nbrave\nfirefox\nlibrewolf\nbadwolf\nwyeb' | ${MYMENU:-dmenu} -p 'select browser:')"
	[ "$browser" ] && ($browser || notify-send 'dmweb' 'sorry, the selected browser is not in $PATH') &>/dev/null
elif [ "$selection" =  "bookmarks" ]; then
	urlalt="$(sed '/^#/d' < ${XDG_DOCUMENTS_DIR:-$HOME/dox}/web/bookmarks | ${MYMENU:-dmenu} -l 5 -p 'bookmarks:' | cut -d'(' -f2- | sed 's/.$//' )"
elif [ "$selection" =  "sites" ]; then
	url="$(sed '/^#/d' < ${XDG_DOCUMENTS_DIR:-$HOME/dox}/web/sites | ${MYMENU:-dmenu} -p 'sites:')"
elif [ "$selection" =  "url" ]; then
	if [ "$MYMENU" = "rofi -dmenu" ];then
		url="$(rofi -dmenu -theme-str 'window {width: 40%;} listview {lines: 0;}' -p 'url:')"
	else
		url="$(${MYMENU:-dmenu} -p 'url:' <&-)"
	fi
elif [ "$selection" =  "google" ]; then
	if [ "$MYMENU" = "rofi -dmenu" ];then
		url="$(rofi -dmenu -theme-str 'listview {lines: 0;}' -p $selection:)"
	else
		url="$(${MYMENU:-dmenu} -p $selection: <&-)"
	fi
elif [ "$selection" =  "youtube" ] || [ "$selection" = "spotify" ]; then
	if [ "$MYMENU" = "rofi -dmenu" ];then
		text="$(rofi -dmenu -theme-str 'listview {lines: 0;}' -p $selection:)"
	else
		text="$(${MYMENU:-dmenu} -p 'query:' <&-)"
	fi
	[ "$text" ] && [ "$selection" =  "youtube" ] && urlalt="https://www.youtube.com/results?search_query=$text"
	[ "$text" ] && [ "$selection" =  "spotify" ] && urlalt="https://open.spotify.com/search/$text"
fi

# more custom than ${MYMENU:-dmenu}
#if [ "$MYMENU" = "dmenu" ] || [ -z "$MYMENU" ]; then
	#notify-send yeas
#fi
# https://www.google.com/search?q=

[ "$url" ] && ${BROWSER:-vimb} "$url" &>/dev/null
[ "$urlalt" ] && ${BROWSERALT:-firefox --new-window} "$urlalt" &>/dev/null
