#!/bin/sh
selection="$(echo -e 'bookmarks\nsites\nurl\ngoogle\nyoutube\nspotify' | ${MYMENU:-dmenu} -p 'browse:')"

if [ "$selection" =  "bookmarks" ]; then
	url="$(sed '/^#/d' < ${XDG_DOCUMENTS_DIR:-$HOME/dox}/web/bookmarks | ${MYMENU:-dmenu} -l 5 -p 'bookmarks:' | cut -d'(' -f2- | sed 's/.$//' )"
elif [ "$selection" =  "sites" ]; then
	url="$(sed '/^#/d' < ${XDG_DOCUMENTS_DIR:-$HOME/dox}/web/sites | ${MYMENU:-dmenu} -p 'sites:')"
elif [ "$selection" =  "url" ]; then
	url="$(${MYMENU:-dmenu} -p 'url:' <&-)"
elif [ "$selection" =  "google" ]; then
	text="$(${MYMENU:-dmenu} -p 'query:' <&-)"
	[ "$text" ] && url="https://www.google.com/search?q=$text"
elif [ "$selection" =  "youtube" ]; then
	text="$(${MYMENU:-dmenu} -p 'query:' <&-)"
	[ "$text" ] && url="https://www.youtube.com/results?search_query=$text"
elif [ "$selection" =  "spotify" ]; then
	text="$(${MYMENU:-dmenu} -p 'query:' <&-)"
	[ "$text" ] && url="https://open.spotify.com/search/$text"
fi

[ "$url" ] && ${BROWSER:-firefox} --new-window "$url"
