#!/bin/sh
bold='[1m'
black='[30m'
red='[31m'
green='[32m'
yellow='[33m'
blue='[34m'
magenta='[35m'
cyan='[36m'
white='[37m'
grey='[90m'
reset='[0m'

lc="${reset}${cyan}"  # labels
nc="${reset}${magenta}"   # user
hn="${reset}${magenta}"     # hostname
ic="${reset}${white}"           # info
c0="${reset}${grey}"            # first color
c1="${reset}${white}"           # second color
c2="${reset}${yellow}"          # third color
c11='[31m'; c12='[32m'
c3='[33m'; c4='[34m'
c5='[35m'; c6='[36m'
c7='[37m'; c8='[38m'
palette="[7m$c11 $c11 $c12 $c12 $c3 $c3 $c4 $c4 $c5 $c5 $c6 $c6 [m"

# $(uptime -p | cut -d' ' -f2-)
cat <<EOF

${c0}        ___         ${nc}${USER}${white}@${reset}${hn}$(cat /etc/hostname)${reset} 
${c0}       (${c1}.. ${c0}|    ${lc}    os        ${ic}$(cat /etc/os-release | grep NAME | head -n1 | cut -d'"' -f2)${reset}
${c0}       (${c2}<> ${c0}|    ${lc}    kernel    ${ic}$(uname -r | cut -d'-' -f1)${reset}
${c0}      /${c1}/  \\ ${c0}\\   ${lc}    shell     ${ic}$(echo $SHELL | rev | cut -d'/' -f1 | rev)${reset}
${c0}     ( ${c1}|  | ${c0}/|  ${lc}    wm        ${ic}${RAM}$(wmctrl -m | grep Name | cut -d' ' -f2)${reset}
${c2}    _${c0}/\\ ${c1}__)${c0}/${c2}_${c0})${reset}
 ${c2}   \/${c0}-____${c2}\/${c6}       ${palette}

EOF

