#!/bin/bash
quicknote="$HOME/dox/notes/quicknote.md"
winclass=$(xdotool search --class quicknote)
if [ -z "$winclass" ]; then
	# quicknote term does not exist
	st -c quicknote -T quicknote -e nvim $quicknote
else
	# quicknote term exists
	if [[ "$(xprop -id $(xdotool search --class quicknote) | grep -i state | cut -d'"' -f35 | cut -d'\' -f1)" == "true" ]]; then
		# and is visible
		xdotool windowunmap "$winclass"
		#xdo hide "$winclass"
	else
		xdotool windowmap "$winclass" && berryc window_center
	fi
fi
