#!/bin/sh
icon=""
voln=$(pamixer --get-volume)
state="$(pamixer --get-mute)"
[ ! "${state##false}" ] && #icon=""
	if [ $voln -lt 45 ] && [ $voln -gt -1 ]; then
		icon=""
	elif [ $voln -lt 73 ] && [ $voln -gt 44 ]; then
		icon=""
	elif [ $voln -gt 72 ]; then
		icon=""
	fi

if [ "$1" = "inc" ]; then
	pamixer -i $2 --allow-boost --set-limit 140
elif [ "$1" = "dec" ]; then
	pamixer -d $2 --allow-boost --set-limit 140
elif [ "$1" = "toggle" ]; then
	pamixer -t
elif [ "$1" = "icon" ]; then
	printf "%s" "$icon"
elif [ "$1" = "notify" ]; then
	notify-send -r 1 -i ~/pix/assets/icons/headphones-solid.svg -a scripts "volume" "$(pamixer --get-volume-human)"
fi
exit
