#!/bin/sh
# run by polybar/dwmblocks every 60 seconds
([ "$1" = "help" ] || [ "$1" = "--help" ] || [ "$1" = "-h" ]) && echo "Usage: sb_battery COMMAND\nCOMMAND:\nperc : shows the percentage\nnotify : sends a notification regarding the current battery info\nicon : echoes a battery icon based on the current battery status\nhelp | -h | --help : prints out this help message"
perc=$(cat /sys/class/power_supply/BAT*/capacity)
state="$(cat /sys/class/power_supply/BAT*/status)"
icon=""

name="bolt-solid.svg"
icon_polybar="󰻹"

# make $perc two digit when single digit
[ $(echo $perc | wc -m) = 2 ] && perc=0$perc 

# set icon according to battery level
[ "${state##Discharging}" ] ||
  if [ $perc -lt 16 ] && [ $perc -gt -1 ]; then
    icon=""
    name="battery-empty-solid.svg"
    icon_polybar="󱢠"
  elif [ $perc -lt 35 ] && [ $perc -gt 15 ]; then
    icon=""
    name="battery-quarter-solid.svg"
    icon_polybar="󰋔"
  elif [ $perc -lt 59 ] && [ $perc -gt 34 ]; then
    icon=""
    name="battery-half-solid.svg"
    icon_polybar="󰛞"
  elif [ $perc -lt 84 ] && [ $perc -gt 58 ]; then
    icon=""
    name="battery-three-quarters-solid.svg"
    icon_polybar="󰛞"
  elif [ $perc -lt 102 ] && [ $perc -gt 83 ]; then
    icon=""
    name="battery-full-solid.svg"
    icon_polybar="󰣐"
  fi

[ "$1" = "" ] && echo "Please give an argument\nUse --help for the available arguments"
[ "$1" = "icon" ] && echo "$icon"
[ "$1" = "icon_polybar" ] && echo "$icon_polybar"
[ "$1" = "perc" ] && echo "$perc"
[ "$1" = "notify_critical" ] && (
    [ $perc -lt 20 ] && [ "$state" = "Discharging" ] && notify-send -r 93433 -i ~/pix/assets/icons/triangle-exclamation-solid.svg -a scripts -u critical -t 8500 "Battery Level Critical" "<i>$perc% / Consider connecting to a power supply.</i>"
    [ $perc -gt 93 ] && [ "$state" = "Charging" ] && notify-send -r 93433 -i ~/pix/assets/icons/$name -a scripts -u normal -t 8500 "Battery Sufficiently Charged " "Please disconnect the power supply."
)
[ "$1" = "notify" ] && notify-send -r 93433 -a scripts -i ~/pix/assets/icons/$name "Battery" "$perc% / $state"
exit
