#!/bin/sh
echo "Timer starting\n$(date '+%a %b %d') $(tput bold)$(date '+%H:%M:%S %P')$(tput sgr0) $(date '+%Z %Y')"
echo "for $1"
sleep $1 && while true; do
sleep 1s
sleep .2
mpv --no-video /home/savar/vids/assets/beep.mp4 &>/dev/null;
done
