#!/bin/sh
histfile="$HOME/.local/share/cache/mpv-vids.txt"
mode="$(echo 'watch now\ndownload\nhistory' | rofi -dmenu -theme-str 'listview {lines: 3;}' -p 'watchvid')"
app=scripts
downicon=~/pix/assets/icons/download-solid.svg
watchicon=~/pix/assets/icons/video-solid.svg

download() {
	echo $link >> $histfile && echo "dl-vid \"$link\"" >> ${HISTFILE:-/home/savar/.local/share/zsh/history} && notify-send -r 15 -i $downicon -a $app "Video" "Downloading into\n~/vids/watch_later" && ( yt-dlp --embed-chapters --embed-subs --write-auto-sub --format="bestvideo[height<=1080]+bestaudio" "$link" -o "/home/savar/vids/watch_later/%(title)s.%(ext)s" || notify-send -r 15 -i $downicon -a $app "Video" "Failed to load video.\nRecheck the url/internet." )
}

watch() {
	echo $link >> $histfile && echo "mpv $link" >> ${HISTFILE:-/home/savar/.local/share/zsh/history} && notify-send -r 15 -i $watchicon -a $app "Video" "Playing in mpv" && ( mpv "$link" || notify-send -r 15 -i $watchicon -a $app "Video" "Failed to load video.\nRecheck the url/internet." )
}

if [ "$mode" = "watch now" ]; then
	link="$(rofi -dmenu -p "play in mpv" -theme-str 'window{width:40%;} listview{lines: 0;}')"
	[ "$link" ] && watch
elif [ "$mode" = "download" ]; then
	link="$(rofi -dmenu -p "download" -theme-str 'window{width:40%;} listview{lines: 0;}')"
	[ "$link" ] && download
elif [ "$mode" = "history" ]; then
	link="$(tac $histfile | rofi -dmenu -theme-str 'window{width: 40%;}' -p 'link')"
	[ "$link" ] && mode="$(echo 'watch now\ndownload' | rofi -dmenu -theme-str 'listview {lines: 2;}' -p 'watchvid')"
	if [ "$mode" = "watch now" ]; then
		watch
	elif [ "$mode" = "download" ]; then
		download
	fi
fi
