#!/bin/sh
## default programs
export TERMINAL="st"
export EDITOR="nvim"
export VISUAL="$TERMINAL -e $EDITOR"
export BROWSER="firefox"
export BROWSERALT="brave"
export MANPAGER='nvim +Man!'

# xdg
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.local/share/cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state
export XDG_RUNTIME_DIR=$HOME/.local/run

export XDG_DESKTOP_DIR="$HOME"
export XDG_DOCUMENTS_DIR="$HOME/dox"
export XDG_DOWNLOAD_DIR="$HOME/dlds"
export XDG_MUSIC_DIR="$HOME/mus"
export XDG_PICTURES_DIR="$HOME/pix"
export XDG_PUBLICSHARE_DIR="/dev/null"
export XDG_TEMPLATES_DIR="/dev/null"
export XDG_VIDEOS_DIR="$HOME/vids"

export PATH="$PATH:$CARGO_HOME/bin:$HOME/.local/bin:$HOME/.local/scripts:$HOME/.local/share/languages/go/bin:$HOME/.local/share/languages/flutter/bin:$HOME/.local/scriptsdwm"
export MANPATH="$HOME/.local/share/man:$MANPATH"

# programs
export PIPEWIRE_RUNTIME_DIR=$XDG_RUNTIME_DIR/pipewire
export NOTESDIR=$HOME/dox/notes
export TODO_PATH=$XDG_DATA_HOME/todo

# fundamental
#export LIBVA_DRIVER_NAME=iHD
#export MOZ_X11_EGL=1

# ~/ cleanup
# languages
LANGS_HOME=$HOME/.local/share/languages
export CARGO_HOME=$LANGS_HOME/rust/cargo
export CARGO_TARGET_DIR=$CARGO_HOME/target
export RUSTUP_HOME=$LANGS_HOME/rust/rustup
export GOPATH=$LANGS_HOME/go
#export XINITRC="$XDG_CONFIG_HOME/x11/initdk"
export XAUTHORITY="$XDG_RUNTIME_DIR/x11/xauth"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/zsh/inputrc"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"

# Other program settings:
export DICS="/usr/share/stardict/dic/"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-R
export LESS_TERMCAP_mb=$'\e[1;31m'
export LESS_TERMCAP_md=$'\e[1;36m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_so=$'\e[01;44;33m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;32m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export QT_QPA_PLATFORMTHEME="qt5ct"
export MOZ_USE_XINPUT2="1" # Mozilla smooth scrolling/touchpads.
#export _JAVA_AWT_WM_NONREPARENTING=1 # Fix for Java applications in dwm
