# Effect
blur=0
blur_layer=1
blur_optimized=1
blur_params_num_passes = 2
blur_params_radius = 5
blur_params_noise = 0.02
blur_params_brightness = 0.9
blur_params_contrast = 0.9
blur_params_saturation = 1.2

shadows = 0
layer_shadows = 0
shadow_only_floating=1
shadows_size = 12
shadows_blur = 15
shadows_position_x = 0
shadows_position_y = 0
shadowscolor= 0x000000ff

border_radius=0
no_radius_when_single=0
focused_opacity=1.0
unfocused_opacity=1.0

# Animation Configuration
animations=1
layer_animations=1
animation_type_open=zoom
animation_type_close=zoom 
layer_animation_type_open=slide
layer_animation_type_close=slide 
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=1
zoom_initial_ratio=0.1
zoom_end_ratio=0.7
fadein_begin_opacity=0.8
fadeout_begin_opacity=0.8
animation_duration_move=500
animation_duration_open=400
animation_duration_tag=500
animation_duration_close=100
animation_duration_focus=0
#animation_duration_focus=400
animation_curve_open=0.46,1.0,0.29,1.1
animation_curve_move=0.46,1.0,0.29,1
animation_curve_tag=0.46,1.0,0.29,1
animation_curve_close=0.08,0.92,0,1
animation_curve_focus=0.46,1.0,0.29,1
animation_curve_opafadeout=0.58,0.98,0.58,0.98
animation_curve_opafadein=0.46,1.0,0.29,1

# Scroller Layout Setting
scroller_structs=0
scroller_default_proportion=0.4
scroller_focus_center=0
scroller_prefer_center=1
edge_scroller_pointer_focus=1
scroller_ignore_proportion_single=1
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.5,0.8,1.0

# Master-Stack Layout Setting
new_is_master=1
smartgaps=0
default_mfact=0.55
default_nmaster=1

#Dwindle Layout Setting
dwindle_smart_split=0
dwindle_drop_simple_split=1
dwindle_manual_split=0
dwindle_hsplit=1
dwindle_vsplit=1
dwindle_preserve_split=1

# Overview Setting
hotarea_size=10
enable_hotarea=1
overviewgappi=5
overviewgappo=30

# Misc
xwayland_persistence=1
syncobj_enable=0
no_border_when_single=0
axis_bind_apply_timeout=100
focus_on_activate=1
sloppyfocus=1
warpcursor=1
focus_cross_monitor=0
focus_cross_tag=0
circle_layout=tile,scroller,monocle
enable_floating_snap=1
snap_distance=50
cursor_size=24
#cursor_theme=Bibata-Modern-Ice
cursor_theme=Simp1e
cursor_hide_timeout=0
drag_tile_to_tile=1
single_scratchpad = 1

# keyboard
numlockon=1
xkb_rules_layout=us,ru
# xkb_rules_options=ctrl:nocaps
# xkb_rules_options=grp:alt_altgr_toggle,caps:hyper

# Trackpad 
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
mouse_natural_scrolling=0
trackpad_natural_scrolling=0
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1
mouse_accel_profile=2
mouse_accel_speed=0.0
# scroll_button=274
# scroll_method=1

# Appearance
gappih=5
gappiv=5
gappoh=20
gappov=20
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=1
rootcolor=0x201b14ff
bordercolor=0x212121ff
focuscolor=0x404040ff
dropcolor=0x8FBA7C55
splitcolor=0xEB441EFF
maximizescreencolor=0xBABD2Cff
urgentcolor=0xad401fff
scratchpadcolor=0xc4939dff
globalcolor=0x8d64cfff
overlaycolor=0x95C381ff

# sub config load
source=./env.conf
source=./bind.conf
source=./rule.conf
source=./monitor.conf
source=./tag.conf
source=./input.conf

# run autostart
exec-once=~/.config/mango/autostart.sh

