# Monitor Rules
# monitorrule=name:eDP-1,width:1920,height:1080,refresh:60,x:0,y:10,scale:1,vrr:0,rr:0
#monitorrule=name:^eDP-1$,scale:0.9,width:1920,height:1200,allow_tearing:0
monitorrule=name:^eDP-1$,disable:1
monitorrule=name:^HDMI-A-1$,scale:1,width:3840,height:2160,allow_tearing:0
