#!/bin/sh
# autostart
setsid -f sxhkd -c ~/.config/berry/sxhkdrc &
if hash picom >/dev/null 2>&1; then
	pkill picom
	setsid -f picom --config $HOME/.config/berry/picom.conf &
fi
# aesthetic but very resource hungry
#if hash picom >/dev/null 2>&1; then
	#pkill picom-ftlabs
	#setsid -f $HOME/.local/bin/picom-ftlabs --config $HOME/.config/picom-ftlabs.conf &
#fi

pkill polybar
$HOME/.config/berry/walls/snippets/$(ls $HOME/.config/berry/walls/snippets/ | shuf | head -n 1)
setsid -f polybar tags &
setsid -f polybar date &
setsid -f polybar power &
setsid -f polybar battery &
setsid -f polybar search &
setsid -f polybar volume &
#setsid -f polybar weather &
#sleep 1 && setsid -f polybar dummy &
#sleep 1 && setsid -f polybar dummy && sleep 1 && polybar-msg -p $(xdotool search --name dummy getwindowpid) cmd toggle &

pkill redshift
redshift -P -O 6500
setsid -f redshift &

pkill dunst
setsid -f dunst &

### quality of life ###
#xwallpaper --zoom "$HOME/.config/berry/walls/$(ls $HOME/.config/berry/walls/ | shuf | head -n 1)"
xset r rate 215 40
xsetroot -cursor_name left_ptr
xrdb -load $HOME/.config/x11/xresources
setxkbmap -option caps:swapescape 

#berryc inner_focus_color 928C73
berryc inner_unfocus_color 2E2E2E
berryc text_focus_color 000000
berryc text_unfocus_color ADA688
berryc inner_border_width 2
berryc border_width 0
berryc title_height 45
berryc edge_gap 10 75 10 10
berryc resize_mask mod4
berryc resize_button 3
