#!/bin/sh

# automatic night light
pkill redshift
redshift -P -O 6500
setsid -f redshift &

# notification daemon
pkill dunst
setsid -f dunst &

### quality of life # rice agnostic ###
xset r rate 215 40
xsetroot -cursor_name left_ptr
xrdb -load $HOME/.config/x11/xresources
setxkbmap -option caps:swapescape 

# resize button
berryc resize_mask mod4
berryc resize_button 3

berrydir=$HOME/.config/berry
exec $berrydir/rices/$(cat $berrydir/activerice)/init
