#!/bin/bash
#pgrep mpd.sh || setsid -f $HOME/.config/dwm/scripts/bar/mpd.sh
[ "$(pgrep eww)" ] || eww daemon
[ "$XDG_SESSION_TYPE" = "wayland" ] && # assumes mangowm
    (
        m="$(mmsg get all-monitors | jq -r '.monitors[] | select(.active) | .name')" &&
            eww open control_center --toggle --screen $m ||
            notify-send "Eww" "Error launching Eww"
        ) ||
    eww-x11 open control_center_dwm --toggle
