#!/bin/sh

# hotkey daemon
pkill sxhkd
setsid -f sxhkd -c ~/.config/berry/rices/pome/sxhkdrc &

# restarting compositor
pkill picom
setsid -f picom --config $HOME/.config/berry/rices/pome/picom.conf &
#pkill fastcompmgr
#setsid -f fastcompmgr -o 0.4 -r 12 -c -C &

#if hash picom >/dev/null 2>&1; then
#	pkill picom
#	setsid -f picom --config $HOME/.config/berry/picom.conf &
#fi
# aesthetic but very resource hungry
#if hash picom >/dev/null 2>&1; then
	#pkill picom-ftlabs
	#setsid -f $HOME/.local/bin/picom-ftlabs --config $HOME/.config/picom-ftlabs.conf &
#fi

# restarting polybar
pkill eww
pkill polybar
setsid -f polybar tags &
setsid -f polybar date &
setsid -f polybar power &
setsid -f polybar battery &
setsid -f polybar search &
setsid -f polybar volume &
#setsid -f polybar weather &
#sleep 1 && setsid -f polybar dummy &
#sleep 1 && setsid -f polybar dummy && sleep 1 && polybar-msg -p $(xdotool search --name dummy getwindowpid) cmd toggle &

# wallpaper
WALLSDIR="$HOME/.config/berry/rices/pome/walls"
$WALLSDIR/snippets/$(ls $WALLSDIR/snippets/ | shuf | head -n 1)

# berry aesthetic
#berryc inner_focus_color 928C73
berryc inner_unfocus_color 2E2E2E
berryc text_focus_color 000000
berryc text_unfocus_color ADA688
berryc inner_border_width 2
berryc border_width 0
berryc title_height 48
berryc edge_gap 10 75 10 10
# this probably requires making the colorscheme more matte like or cozy
# xwallpaper --zoom "$HOME/.config/berry/walls/whatever2.png" && berryc inner_border_width 0 && berryc title_height 52 && berryc inner_focus_color 303030 && berryc inner_unfocus_color 252525 && berryc text_focus_color ADA688
