#!/bin/sh
export XAUTHORITY="$HOME/.local/run/x11/xauth"
setsid -f $HOME/.config/dwm/autostart.sh &
#export MYMENU="dmenu"
export MYMENU="dmenu"
export XDG_SESSION_TYPE=x11

#while :; do
#	ssh-agent dwm
#done

xrandr --output eDP-1 --scale 1.1x1.1
xrandr --output HDMI-A-1 --scale 1.1x1.1
#ulimit -n 1048576
exec dbus-run-session dwm
#exec dbus-launch --exit-with-session dwm
#exec dwm
