#!/bin/sh
selection="$(echo 'fullscreen\ncustom' | rofi -dmenu -p "selection")"
[ "$selection" ] && name="$(echo untitled | rofi -dmenu -p 'name')" && name=${name%.png}
[ "$name" ] && time=$(echo 1 | rofi -dmenu -p 'specify delay (in integral seconds)')
[ "$time" ] && (
  [ ! "${selection##custom}" ] && scrot -s -d $time "$HOME/pix/screenshots/$name.png" && notify-send -i $HOME/pix/screenshots/$name.png "Screenshot Taken!"
  [ ! "${selection##fullscreen}" ] && scrot -d $time "$HOME/pix/screenshots/$name.png" && notify-send -i $HOME/pix/screenshots/$name.png "Screenshot Taken!"
  )
exit
